/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_kpa_nativ_NativeDaemonAPIK */

#ifndef _Included_com_android_kpa_nativ_NativeDaemonAPIK
#define _Included_com_android_kpa_nativ_NativeDaemonAPIK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_android_kpa_nativ_NativeDaemonAPIK_doDaemon
 * Method:    doDaemon
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_keepa_kpa_nativ_NativeDaemonAPIK_doDaemon
  (JNIEnv *, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
