/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_marswin89_marsdaemon_nativ_NativeDaemonAPI21 */

#ifndef _Included_com_android_kpa_nativ_NativeDaemonAPIL
#define _Included_com_android_kpa_nativ_NativeDaemonAPIL
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_marswin89_marsdaemon_nativ_NativeDaemonAPI21
 * Method:    doDaemon
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_keepa_kpa_nativ_NativeDaemonAPIL_doDaemon
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
